<?php
define("FFMPEG","C:/Bitnami/wampstack-7.3.18-1/apache2/htdocs/ffmpeg/bin/ffmpeg");
define("THUMBNAIL_PATH","C:/Bitnami/wampstack-7.3.18-1/apache2/htdocs/policecrimestoppers/tmp");
define("GOOGLE_CLIENT_ID","992582993320-mlcdu3rrjnfnoot72oeioaacpp5cjnhc.apps.googleusercontent.com");
define("ROOT_PATH","C:/Bitnami/wampstack-7.3.18-1/apache2/htdocs/policecrimestoppers");
define("SITE_URL","http://local.policecrimestoppers.com");
define("SUBSCRIBER_COUNT",number_format(674983));
define("SENDER_EMAIL","pauljuniorgeorge@gmail.com");
?>
